create table address (id bigint not null auto_increment, city varchar(30), line1 varchar(50), line2 varchar(50), postal_code varchar(255), `use` varchar(255), country_code_id bigint, demographics_id bigint, state_code_id bigint, primary key (id)) ENGINE=InnoDB;
create table address_aud (id bigint not null, rev integer not null, revtype tinyint, city varchar(255), line1 varchar(255), line2 varchar(255), postal_code varchar(255), `use` varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table administrative_gender_code (id bigint not null auto_increment, code varchar(255) not null, code_system varchar(255), code_system_name varchar(255) not null, code_systemoid varchar(255), description varchar(255), display_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table country_code (id bigint not null auto_increment, code varchar(255) not null, code_system varchar(255), code_system_name varchar(255) not null, code_systemoid varchar(255), description varchar(255), display_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table demographics (id bigint not null auto_increment, birth_day datetime, first_name varchar(100) not null, last_name varchar(100) not null, middle_name varchar(100), administrative_gender_code_id bigint, primary key (id)) ENGINE=InnoDB;
create table demographics_aud (id bigint not null, rev integer not null, revtype tinyint, birth_day datetime, first_name varchar(255), last_name varchar(255), middle_name varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table demographics_identifiers (demographics_id bigint not null, identifiers_id bigint not null) ENGINE=InnoDB;
create table demographics_identifiers_aud (rev integer not null, demographics_id bigint not null, identifiers_id bigint not null, revtype tinyint, primary key (rev, demographics_id, identifiers_id)) ENGINE=InnoDB;
create table identifier (id bigint not null auto_increment, value varchar(255) not null, identifier_system_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table identifier_aud (id bigint not null, rev integer not null, revtype tinyint, value varchar(255), identifier_system_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table identifier_system_aud (id bigint not null, rev integer not null, revtype tinyint, display varchar(255), oid varchar(255), reassignable bit, system varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table identifier_system (id bigint not null auto_increment, display varchar(255), oid varchar(255), reassignable bit not null, system varchar(255), primary key (id)) ENGINE=InnoDB;
create table locale (id bigint not null auto_increment, code varchar(255) not null, code_system varchar(255), code_system_name varchar(255) not null, code_systemoid varchar(255), description varchar(255), display_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table patient (id bigint not null auto_increment, registration_purpose_email varchar(255), demographics_id bigint, primary key (id)) ENGINE=InnoDB;
create table relationship (role_id bigint not null, primary key (role_id)) ENGINE=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) ENGINE=InnoDB;
create table role (id bigint not null auto_increment, code varchar(255) not null, name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table role_aud (id bigint not null, rev integer not null, revtype tinyint, code varchar(255), name varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table role_scopes (roles_id bigint not null, scopes_id bigint not null, primary key (roles_id, scopes_id)) ENGINE=InnoDB;
create table role_scopes_aud (rev integer not null, roles_id bigint not null, scopes_id bigint not null, revtype tinyint, primary key (rev, roles_id, scopes_id)) ENGINE=InnoDB;
create table scope (id bigint not null auto_increment, scope_description varchar(255) not null, scope_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table scope_aud (id bigint not null, rev integer not null, revtype tinyint, scope_description varchar(255), scope_name varchar(255), primary key (id, rev)) ENGINE=InnoDB;
create table state_code (id bigint not null auto_increment, code varchar(255) not null, code_system varchar(255), code_system_name varchar(255) not null, code_systemoid varchar(255), description varchar(255), display_name varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table telecom (id bigint not null auto_increment, system varchar(255) not null, `use` varchar(255), value varchar(150) not null, demographics_id bigint, primary key (id)) ENGINE=InnoDB;
create table telecom_aud (id bigint not null, rev integer not null, revtype tinyint, system varchar(255), `use` varchar(255), value varchar(255), demographics_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table user (id bigint not null auto_increment, disabled bit not null, user_auth_id varchar(255), demographics_id bigint, locale_id bigint, primary key (id)) ENGINE=InnoDB;
create table user_activation_aud (id bigint not null, rev integer not null, revtype tinyint, email_token varchar(255), email_token_expiration datetime, verification_code varchar(255), verified bit, user_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table user_aud (id bigint not null, rev integer not null, revtype tinyint, disabled bit, user_auth_id varchar(255), demographics_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table user_roles (users_id bigint not null, roles_id bigint not null, primary key (users_id, roles_id)) ENGINE=InnoDB;
create table user_roles_aud (rev integer not null, users_id bigint not null, roles_id bigint not null, revtype tinyint, primary key (rev, users_id, roles_id)) ENGINE=InnoDB;
create table user_scope_assignment_aud (id bigint not null, rev integer not null, revtype tinyint, assigned bit, scope_id bigint, user_activation_id bigint, primary key (id, rev)) ENGINE=InnoDB;
create table user_activation (id bigint not null auto_increment, email_token varchar(255) not null, email_token_expiration datetime not null, verification_code varchar(255) not null, verified bit not null, user_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table user_patient_relationship (user_id bigint not null, patient_id bigint not null, relationship_role_id bigint not null, primary key (patient_id, relationship_role_id, user_id)) ENGINE=InnoDB;
create table user_scope_assignment (id bigint not null auto_increment, assigned bit not null, scope_id bigint, user_activation_id bigint, primary key (id)) ENGINE=InnoDB;
alter table identifier add constraint identifier_idx unique (value, identifier_system_id);
alter table identifier_system add constraint system_idx unique (system);
alter table user_activation add constraint email_token_idx unique (email_token);
alter table user_scope_assignment add constraint UK89m6kbqn388uowpe9ph77ruwt unique (user_activation_id, scope_id);
alter table address add constraint FK2apbqk15r1fk1ce5c3dfs1ndn foreign key (country_code_id) references country_code (id);
alter table address add constraint FK4s6v8tnwdssaad9pvbpxxww26 foreign key (demographics_id) references demographics (id);
alter table address add constraint FKbqj2j4pyht7nxbxqdwcr9ei87 foreign key (state_code_id) references state_code (id);
alter table address_aud add constraint FKcc7vlgg86eqe1dmvivbkv046v foreign key (rev) references revinfo (rev);
alter table demographics add constraint FKth4oabffvjwonyb2yd73d8l1p foreign key (administrative_gender_code_id) references administrative_gender_code (id);
alter table demographics_aud add constraint FKj5txfm6up1klfqp8t169wtxxm foreign key (rev) references revinfo (rev);
alter table demographics_identifiers add constraint FKbi0pyfxxaul718v9h63qu1mci foreign key (identifiers_id) references identifier (id);
alter table demographics_identifiers add constraint FK3ci48lwo89sk363c8c5jk3xr0 foreign key (demographics_id) references demographics (id);
alter table demographics_identifiers_aud add constraint FKmof5bycmsdyrsetat0ceosmrd foreign key (rev) references revinfo (rev);
alter table identifier add constraint FKjme4ro8hpoeclf3aq4v6apgq1 foreign key (identifier_system_id) references identifier_system (id);
alter table identifier_aud add constraint FK63r2o3ax4xn4e9fbe78r59l21 foreign key (rev) references revinfo (rev);
alter table identifier_system_aud add constraint FK6qm7poucoodtuae6v1nvf7pfv foreign key (rev) references revinfo (rev);
alter table patient add constraint FK2vbcmahxhdltsjwfhlg9nxdrv foreign key (demographics_id) references demographics (id);
alter table relationship add constraint FKrs9kp18yr2fwale7ammcm07b6 foreign key (role_id) references role (id);
alter table role_aud add constraint FKrks7qtsmup3w81fdp0d6omfk7 foreign key (rev) references revinfo (rev);
alter table role_scopes add constraint FK7qfwaml7g6mtnl6w4xm9be0hp foreign key (scopes_id) references scope (id);
alter table role_scopes add constraint FKj4benp61mf5m7wnast2llih1 foreign key (roles_id) references role (id);
alter table role_scopes_aud add constraint FKhi78gervneyp2v5aw2ky5l0p6 foreign key (rev) references revinfo (rev);
alter table scope_aud add constraint FKqvi4bxfyyv068d1x8gff1gsid foreign key (rev) references revinfo (rev);
alter table telecom add constraint FKef2vqks3gvmws7cxg84pxucx foreign key (demographics_id) references demographics (id);
alter table telecom_aud add constraint FKix3c360mmqvddy76o1m46ihar foreign key (rev) references revinfo (rev);
alter table user add constraint FKoacji0w1da8jv5yqpnyxvxv5t foreign key (demographics_id) references demographics (id);
alter table user add constraint FKfbdc5480okukpuvd43xidfahh foreign key (locale_id) references locale (id);
alter table user_activation_aud add constraint FK9re0c59t3i31p2ujugy4tujpk foreign key (rev) references revinfo (rev);
alter table user_aud add constraint FK89ntto9kobwahrwxbne2nqcnr foreign key (rev) references revinfo (rev);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK7ecyobaa59vxkxckg6t355l86 foreign key (users_id) references user (id);
alter table user_roles_aud add constraint FKox6xyy64fyq0y3dvv5ve53a0h foreign key (rev) references revinfo (rev);
alter table user_scope_assignment_aud add constraint FKrgqa5ttc70311wm8a2g5x9p1i foreign key (rev) references revinfo (rev);
alter table user_activation add constraint FKidgebcgp5cij94pf1tup1f62p foreign key (user_id) references user (id);
alter table user_patient_relationship add constraint FKcueft195i7ut2u6mddio89uvc foreign key (user_id) references user (id);
alter table user_patient_relationship add constraint FKg70k723dfb4benj3lv2rjhp76 foreign key (patient_id) references patient (id);
alter table user_patient_relationship add constraint FK52xkj4gtw7jsy4ndcf24ce1sc foreign key (relationship_role_id) references relationship (role_id);
alter table user_scope_assignment add constraint FKmvcfov9puvk2higv7h54wbyii foreign key (scope_id) references scope (id);
alter table user_scope_assignment add constraint FKtldupmh35x5ragy1g4x2wcj84 foreign key (user_activation_id) references user_activation (id);